### PR TITLE
Fix Ajith sir's surname

### PR DESCRIPTION
**Pull request by someshkar**
It's Ajithkumar K.G., not A.G.

### CODE REVIEW

**Comment by ananay** [comment]
lgtm

**Comment by someshkar** [comment]
long time sir :pray:

**Comment by ananay** [comment]
long time no see how u doing

**Comment by someshkar** [comment]
all good all good

**Comment by ananay** [comment]
great to hear what are you upto these days

**Comment by someshkar** [comment]
well yahi doing an internship, still writing React, still not making my own email servers :stuck_out_tongue:

**Pull request merged**
